-- SQL Schema for The Daily Dough Supabase Database

-- 1. Tenants (Businesses) Table
CREATE TABLE IF NOT EXISTS bakery_tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL, -- e.g., 'the-daily-dough', 'mama-bread'
    business_type TEXT DEFAULT 'BAKERY', -- 'BAKERY', 'RETAIL', 'RESTAURANT'
    description TEXT,
    logo_url TEXT,
    primary_color TEXT DEFAULT '#7D8F69',
    secondary_color TEXT DEFAULT '#D88569',
    oven_capacity INTEGER DEFAULT 6,
    default_bake_temp INTEGER DEFAULT 450,
    default_steam_time INTEGER DEFAULT 15,
    default_bake_time TEXT DEFAULT '45m',
    address TEXT,
    phone TEXT,
    email TEXT,
    stripe_account_id TEXT, -- For Stripe Connect or separate accounts
    subscription_status TEXT DEFAULT 'TRIAL', -- 'TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED'
    subscription_plan TEXT DEFAULT 'BASIC', -- 'BASIC', 'PRO', 'ENTERPRISE'
    subscription_id TEXT, -- Stripe Subscription ID
    onboarding_completed BOOLEAN DEFAULT FALSE,
    twilio_config JSONB, -- Optional bakery-specific Twilio credentials
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Recipes Table
CREATE TABLE IF NOT EXISTS bakery_recipes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    true_hydration DECIMAL(5, 4),
    flavor_profile TEXT,
    ingredients JSONB NOT NULL,
    images TEXT[] DEFAULT '{}',
    prep_time_minutes INTEGER DEFAULT 0,
    bake_time_minutes INTEGER DEFAULT 45,
    is_hidden BOOLEAN DEFAULT FALSE,
    sku TEXT, -- Stock Keeping Unit for Retail
    barcode TEXT, -- Barcode/EAN for Retail
    product_type TEXT DEFAULT 'PHYSICAL', -- 'PHYSICAL', 'SERVICE', 'DIGITAL'
    available_addons JSONB DEFAULT '[]', -- List of possible customizations
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Orders Table
CREATE TABLE IF NOT EXISTS bakery_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    order_id TEXT UNIQUE NOT NULL, -- Public order ID (e.g., XQYX99)
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_email TEXT,
    notification_preference TEXT,
    customer_id TEXT, -- 'guest' or Auth User ID
    total_price DECIMAL(10, 2) NOT NULL,
    fulfillment_type TEXT NOT NULL, -- 'PICKUP' or 'SHIPPING'
    items JSONB NOT NULL,
    notes TEXT,
    pickup_date TEXT, -- YYYY-MM-DD
    order_source TEXT DEFAULT 'ONLINE', -- 'ONLINE', 'PHONE', 'WALK_IN'
    status TEXT DEFAULT 'PENDING',
    payment_status TEXT DEFAULT 'PENDING', -- 'PENDING', 'PAID', 'FAILED', 'REFUNDED'
    table_number TEXT, -- For Restaurant mode
    promo_code TEXT,
    discount_applied DECIMAL(10, 2) DEFAULT 0,
    payment_method JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure newer notification fields exist on existing installs
ALTER TABLE IF EXISTS bakery_orders
    ADD COLUMN IF NOT EXISTS customer_email TEXT;

ALTER TABLE IF EXISTS bakery_orders
    ADD COLUMN IF NOT EXISTS notification_preference TEXT;

-- 4. Reviews Table
CREATE TABLE IF NOT EXISTS bakery_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    recipe_id UUID REFERENCES bakery_recipes(id) ON DELETE CASCADE,
    customer_id TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    reply TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Subscriptions Table
CREATE TABLE IF NOT EXISTS bakery_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    customer_id TEXT NOT NULL,
    recipe_id UUID REFERENCES bakery_recipes(id),
    recipe_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    frequency TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    start_date TEXT NOT NULL,
    next_bake_date TEXT NOT NULL,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Promo Codes Table
CREATE TABLE IF NOT EXISTS bakery_promos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    code TEXT NOT NULL, -- Code is unique within a tenant
    type TEXT NOT NULL, -- 'FIXED', 'PERCENT', 'FREE_LOAF'
    value DECIMAL(10, 2) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    usage_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tenant_id, code)
);

-- 7. Inventory Table
CREATE TABLE IF NOT EXISTS bakery_inventory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    ingredient_name TEXT NOT NULL,
    current_stock DECIMAL(10, 2) DEFAULT 0, -- in grams
    unit TEXT DEFAULT 'g',
    min_stock_threshold DECIMAL(10, 2) DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tenant_id, ingredient_name)
);

-- Ingredient cost defaults (per tenant)
CREATE TABLE IF NOT EXISTS bakery_ingredient_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    bulk_price DECIMAL(10, 4),
    bulk_weight DECIMAL(10, 4),
    cost_per_unit DECIMAL(10, 4), -- cost per 100g fallback
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tenant_id, name)
);

-- 8. Forecasts Table
CREATE TABLE IF NOT EXISTS bakery_forecasts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    horizon_days INTEGER DEFAULT 30,
    method TEXT DEFAULT 'SIMPLE_TREND',
    confidence_level TEXT DEFAULT 'MEDIUM',
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Forecast Items Table
CREATE TABLE IF NOT EXISTS bakery_forecast_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    forecast_id UUID REFERENCES bakery_forecasts(id) ON DELETE CASCADE,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    forecast_date TEXT NOT NULL,
    recipe_id UUID REFERENCES bakery_recipes(id) ON DELETE SET NULL,
    recipe_name TEXT NOT NULL,
    forecast_units INTEGER DEFAULT 0,
    forecast_revenue DECIMAL(10, 2) DEFAULT 0,
    order_source TEXT DEFAULT 'ALL',
    confidence_score DECIMAL(5, 2) DEFAULT 0
);

-- 10. Top Sellers Snapshot Table
CREATE TABLE IF NOT EXISTS bakery_top_sellers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. Top Seller Items Table
CREATE TABLE IF NOT EXISTS bakery_top_seller_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    top_seller_id UUID REFERENCES bakery_top_sellers(id) ON DELETE CASCADE,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    recipe_id UUID REFERENCES bakery_recipes(id) ON DELETE SET NULL,
    recipe_name TEXT NOT NULL,
    units_sold INTEGER DEFAULT 0,
    revenue DECIMAL(10, 2) DEFAULT 0,
    rank INTEGER DEFAULT 0
);

-- 12. Supply Plan Snapshot Table
CREATE TABLE IF NOT EXISTS bakery_supply_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    lead_time_days INTEGER DEFAULT 7,
    safety_buffer_grams DECIMAL(10, 2) DEFAULT 5000,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. Supply Plan Items Table
CREATE TABLE IF NOT EXISTS bakery_supply_plan_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    supply_plan_id UUID REFERENCES bakery_supply_plans(id) ON DELETE CASCADE,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    ingredient_name TEXT NOT NULL,
    current_stock DECIMAL(10, 2) DEFAULT 0,
    forecast_need DECIMAL(10, 2) DEFAULT 0,
    reorder_amount DECIMAL(10, 2) DEFAULT 0,
    unit TEXT DEFAULT 'g'
);

-- 8. Audit Logs Table (For consulting and business tracking)
CREATE TABLE IF NOT EXISTS bakery_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    user_id UUID,
    action TEXT NOT NULL, -- 'ORDER_CREATED', 'RECIPE_UPDATED', 'SETTINGS_CHANGED', etc.
    entity_type TEXT, -- 'ORDER', 'RECIPE', 'TENANT', etc.
    entity_id TEXT,
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Enable Row Level Security (RLS) on all tables
ALTER TABLE bakery_tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_promos ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_forecasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_forecast_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_top_sellers ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_top_seller_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_supply_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_supply_plan_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE bakery_ingredient_costs ENABLE ROW LEVEL SECURITY;

-- 10. Create Policies

-- 9.1 bakery_tenants Policies
-- Anyone can view bakery info (needed for storefronts)
CREATE POLICY "Public profiles are viewable by everyone"
ON bakery_tenants FOR SELECT
USING (true);

-- Only the bakery owner can update their profile
CREATE POLICY "Users can update their own bakery profile"
ON bakery_tenants FOR UPDATE
USING ((auth.jwt()->>'sub')::uuid = id OR (auth.jwt()->'user_metadata'->>'tenant_id')::uuid = id);

-- Allow bakery registration (insert)
CREATE POLICY "Allow bakery registration"
ON bakery_tenants FOR INSERT
WITH CHECK (true);

-- 9.2 bakery_recipes Policies
-- Anyone can view recipes (needed for storefronts)
CREATE POLICY "Recipes are viewable by everyone"
ON bakery_recipes FOR SELECT
USING (true);

-- Only the bakery owner can insert recipes
CREATE POLICY "Bakers can insert their own recipes"
ON bakery_recipes FOR INSERT
WITH CHECK ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- Only the bakery owner can update recipes
CREATE POLICY "Bakers can update their own recipes"
ON bakery_recipes FOR UPDATE
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- Only the bakery owner can delete recipes
CREATE POLICY "Bakers can delete their own recipes"
ON bakery_recipes FOR DELETE
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 9.3 bakery_orders Policies
-- Bakers can see all orders for their bakery
CREATE POLICY "Bakers can see their own bakery orders"
ON bakery_orders FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- Customers can see their own orders (if they are logged in)
CREATE POLICY "Customers can see their own orders"
ON bakery_orders FOR SELECT
USING (auth.uid()::text = customer_id);

-- Allow anonymous order placement (insert)
CREATE POLICY "Allow anonymous order placement"
ON bakery_orders FOR INSERT
WITH CHECK (true);

-- 9.4 bakery_reviews Policies
-- Anyone can view reviews
CREATE POLICY "Reviews are viewable by everyone"
ON bakery_reviews FOR SELECT
USING (true);

-- Logged in customers can create reviews
CREATE POLICY "Authenticated users can create reviews"
ON bakery_reviews FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

-- Users can update/delete their own reviews
CREATE POLICY "Users can manage their own reviews"
ON bakery_reviews FOR ALL
USING (auth.uid()::text = customer_id);

-- Bakers can reply to reviews in their bakery
CREATE POLICY "Bakers can manage reviews for their bakery"
ON bakery_reviews FOR UPDATE
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 9.5 bakery_subscriptions Policies
-- Bakers can see all subscriptions for their bakery
CREATE POLICY "Bakers can see their own bakery subscriptions"
ON bakery_subscriptions FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- Customers can see their own subscriptions
CREATE POLICY "Customers can see their own subscriptions"
ON bakery_subscriptions FOR SELECT
USING (auth.uid()::text = customer_id);

-- 9.6 bakery_promos Policies
-- Anyone can check a promo code (view)
CREATE POLICY "Promos are viewable by everyone"
ON bakery_promos FOR SELECT
USING (true);

-- Only bakers can manage promos
CREATE POLICY "Bakers can manage their own promos"
ON bakery_promos FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.7 bakery_inventory Policies
-- Only bakers can see/manage inventory
CREATE POLICY "Bakers can manage their own inventory"
ON bakery_inventory FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.8 bakery_audit_logs Policies
-- Only bakers can see their audit logs
CREATE POLICY "Bakers can see their own audit logs"
ON bakery_audit_logs FOR SELECT
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.9 bakery_forecasts Policies
CREATE POLICY "Bakers can manage their own forecasts"
ON bakery_forecasts FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.10 bakery_forecast_items Policies
CREATE POLICY "Bakers can manage their own forecast items"
ON bakery_forecast_items FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.11 bakery_top_sellers Policies
CREATE POLICY "Bakers can manage their own top seller snapshots"
ON bakery_top_sellers FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.12 bakery_top_seller_items Policies
CREATE POLICY "Bakers can manage their own top seller items"
ON bakery_top_seller_items FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.13 bakery_supply_plans Policies
CREATE POLICY "Bakers can manage their own supply plans"
ON bakery_supply_plans FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.14 bakery_supply_plan_items Policies
CREATE POLICY "Bakers can manage their own supply plan items"
ON bakery_supply_plan_items FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);

-- 10.15 bakery_ingredient_costs Policies
CREATE POLICY "Bakers can manage their own ingredient costs"
ON bakery_ingredient_costs FOR ALL
USING ((auth.jwt()->'user_metadata'->>'tenant_id')::uuid = tenant_id);
