-- SQL Schema for The Daily Dough Supabase Database

-- 1. Tenants (Bakeries) Table
CREATE TABLE IF NOT EXISTS bakery_tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL, -- e.g., 'the-daily-dough', 'mama-bread'
    description TEXT,
    logo_url TEXT,
    primary_color TEXT DEFAULT '#7D8F69',
    secondary_color TEXT DEFAULT '#D88569',
    stripe_account_id TEXT, -- For Stripe Connect or separate accounts
    twilio_config JSONB, -- Optional bakery-specific Twilio credentials
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Recipes Table
CREATE TABLE IF NOT EXISTS bakery_recipes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    true_hydration DECIMAL(5, 4),
    ingredients JSONB NOT NULL,
    images TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Orders Table
CREATE TABLE IF NOT EXISTS bakery_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    order_id TEXT UNIQUE NOT NULL, -- Public order ID (e.g., XQYX99)
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_id TEXT, -- 'guest' or Auth User ID
    total_price DECIMAL(10, 2) NOT NULL,
    fulfillment_type TEXT NOT NULL, -- 'PICKUP' or 'SHIPPING'
    items JSONB NOT NULL,
    notes TEXT,
    pickup_date TEXT, -- YYYY-MM-DD
    status TEXT DEFAULT 'PENDING',
    promo_code TEXT,
    discount_applied DECIMAL(10, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Reviews Table
CREATE TABLE IF NOT EXISTS bakery_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    recipe_id UUID REFERENCES bakery_recipes(id) ON DELETE CASCADE,
    customer_id TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Subscriptions Table
CREATE TABLE IF NOT EXISTS bakery_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    customer_id TEXT NOT NULL,
    recipe_id UUID REFERENCES bakery_recipes(id),
    recipe_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    frequency TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    start_date TEXT NOT NULL,
    next_bake_date TEXT NOT NULL,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Promo Codes Table
CREATE TABLE IF NOT EXISTS bakery_promos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES bakery_tenants(id) ON DELETE CASCADE,
    code TEXT NOT NULL, -- Code is unique within a tenant
    type TEXT NOT NULL, -- 'FIXED', 'PERCENT', 'FREE_LOAF'
    value DECIMAL(10, 2) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    usage_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tenant_id, code)
);
